### ISSUE TITLE
question

### ISSUE THREAD

**Issue by hunim** [Geodan/pg2b3dm#53]
![image](https://user-images.githubusercontent.com/31200984/88282425-2151aa80-cd1c-11ea-8d33-39012f0d5bb2.png)
Follow your documentation step by step, but hint at the problem.How can I solve this problem?The data was downloaded from the link you provided.

**Comment by bertt** [comment]
Hi, I can't reproduce the error when following the steps in https://github.com/Geodan/pg2b3dm/blob/master/getting_started.md

Looking at the error it says there are MultiPolygon geometries in the column delaware_buildings.geom. I've checked this table, it should have column 'wkb-geometry' instead of column 'geom' you use in the -i parameter. I've checked the column 'wkb_geometry' and it does only contains Polygon geometries not MultiPolygons.

**Comment by hunim** [comment]
Thank you very much for your answer.When I import my data drawn in ArcMap into Postgresql, Use this statement ` CREATE TABLE polygon_table AS SELECT gid, height, (ST_DUMP(geom)).geom::geometry(Polygon) AS geom FROM delaware_buildings  `can solve this  problem. ArcMap creates MutiPolygon by default.

**Comment by bertt** [comment]
Ok great
